const ADD_AD = 'ADD_AD';
const UPDATE_AD = 'UPDATE_AD';
const REMOVE_AD = 'REMOVE_AD';

const USERS_REQUESTED = 'USERS_REQUESTED';
const USERS_RECEIVED = 'USERS_RECEIVED';
const USERS_FAILED = 'USERS_FAILED';

export {
    ADD_AD,
    UPDATE_AD,
    REMOVE_AD,

    USERS_REQUESTED,
    USERS_RECEIVED,
    USERS_FAILED
};